Rscript read_RDS.R output/test_MA_p0_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p10_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p20_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p30_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p40_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p50_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p60_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p70_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p80_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p90_brca_log_cm.RDS
Rscript read_RDS.R output/test_MA_p100_brca_log_cm.RDS
