Rscript read_RDS.R output/test_MA_p0_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p10_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p20_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p30_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p40_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p50_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p60_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p70_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p80_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p90_brca_npn_cm.RDS
Rscript read_RDS.R output/test_MA_p100_brca_npn_cm.RDS
